version: "3"

services:
  nextjs:
    container_name: nextjs
    build:
      context: .. # root of the project
      dockerfile: docker/next/Dockerfile
    env_file:
      - ../.env
    ports:
      - 3000:3000
